function [Z, P_Z_fun, P_Z_obs] = gen_Z(W,T,b_z)
    G   = size(W,1);
    eta = randn(G,1,2);
    Z   = zeros(G,1,2);
    X   = @(i,W,T) [ones(size(W,1),1), W(:,:,i), W(:,:,3-i), T(:,:,i), T(:,:,3-i)];

    for i =1:2
        Z(:,1,i) = eta(:,1,i) <= X(i,W,T)*b_z;
    end
    
    % Pr(Z=(z1,z2)|W)
    P_Z     = @(i,W,T,b_z) normcdf( X(i,W,T)*b_z );

    P_Z_fun = @(i,z1,z2,W,T,b_z) ...
            (z1==1 & z2==1)*    P_Z(i,W,T,b_z).*    P_Z(3-i,W,T,b_z)  ...
        +   (z1==1 & z2==0)*    P_Z(i,W,T,b_z).* (1-P_Z(3-i,W,T,b_z)) ...
        +   (z1==0 & z2==1)* (1-P_Z(i,W,T,b_z)).*   P_Z(3-i,W,T,b_z)  ...
        +   (z1==0 & z2==0)* (1-P_Z(i,W,T,b_z)).*(1-P_Z(3-i,W,T,b_z));
        
    P_Z_obs = cat(3, ...
        [P_Z_fun(1,1,1,W,T,b_z), P_Z_fun(1,1,0,W,T,b_z),  ...
         P_Z_fun(1,0,1,W,T,b_z), P_Z_fun(1,0,0,W,T,b_z)], ...
        [P_Z_fun(2,1,1,W,T,b_z), P_Z_fun(2,1,0,W,T,b_z),  ...
         P_Z_fun(2,0,1,W,T,b_z), P_Z_fun(2,0,0,W,T,b_z)] );
end